version: '2'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - VIRTUAL_HOST=db.${HOSTNAME}
      - HTTPS_METHOD=nohttp
      - PMA_ARBITRARY=1
    networks:
      - local_web
      - local_db

networks:
  local_db:
    external: true
  local_web:
    external: true
