version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /var/docker/vhosts:/etc/nginx/vhost.d:ro
    ports:
      - "8090:80"
    networks:
      - local_web

networks:
  local_web:
    external: true

