version: '2'

services:
  wp:
    image: php:mysqli
    container_name: wp.%URL%
    volumes:
      - %WEBDIR%/%URL%:/var/www/html
      - /var/run/mysqld/mysqld.sock:/tmp/mysqld.sock
    environment:
      - VIRTUAL_HOST=%URL%,*.%URL%
      - WORDPRESS_DB_HOST=localhost:/tmp/mysqld.sock
      - WORDPRESS_DB_USER=%DBNAME%
      - WORDPRESS_DB_NAME=%DBNAME%
      - WORDPRESS_DB_PASSWORD=%DBPWD%
    networks:
      - default
      - local_web

networks:
  local_web:
    external: true
